# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170117_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Separator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '___________________',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Empresa', 'verbose_name_plural': ' 2. Empresas'},
        ),
        migrations.AlterModelOptions(
            name='companyemail',
            options={'ordering': ['id'], 'verbose_name': 'Email', 'verbose_name_plural': '2.2 Emails'},
        ),
        migrations.AlterModelOptions(
            name='companyphonenumber',
            options={'ordering': ['id'], 'verbose_name': 'Tel\xe9fono', 'verbose_name_plural': ' 2.1 Tel\xe9fonos'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': ' 1. Contactos'},
        ),
        migrations.AlterModelOptions(
            name='productdepartment',
            options={'ordering': ['id'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Productos 1. Familias'},
        ),
        migrations.AlterModelOptions(
            name='productforsale',
            options={'ordering': ['code'], 'verbose_name': 'Producto para la Venta', 'verbose_name_plural': 'Productos 3. Productos para la Venta'},
        ),
        migrations.AlterModelOptions(
            name='productsubdepartment',
            options={'ordering': ['id'], 'verbose_name': 'Sub-Familia', 'verbose_name_plural': 'Productos 2. Sub-Familias'},
        ),
    ]
