# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170118_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Separator',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='companyemail',
            options={'ordering': ['id'], 'verbose_name': 'Email', 'verbose_name_plural': 'Empresas 2. Emails'},
        ),
        migrations.AlterModelOptions(
            name='companyphonenumber',
            options={'ordering': ['id'], 'verbose_name': 'Tel\xe9fono', 'verbose_name_plural': 'Empresas 1. Tel\xe9fonos'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': ' Contactos'},
        ),
        migrations.AddField(
            model_name='currency',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
