# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20170118_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='identifier',
            field=models.CharField(default='CRC', max_length=3, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
