# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_currency_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='CRC', max_length=3, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='currency',
            name='identifier',
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('company', 'code')]),
        ),
    ]
