# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20170118_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='department',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subdepartment',
        ),
        migrations.AlterUniqueTogether(
            name='productdepartment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productdepartment',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='productforsale',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productforsale',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productforsale',
            name='department',
        ),
        migrations.RemoveField(
            model_name='productforsale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productforsale',
            name='subdepartment',
        ),
        migrations.AlterUniqueTogether(
            name='productsubdepartment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productsubdepartment',
            name='department',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductDepartment',
        ),
        migrations.DeleteModel(
            name='ProductForSale',
        ),
        migrations.DeleteModel(
            name='ProductSubDepartment',
        ),
    ]
