# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0007_auto_20170118_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=3, verbose_name='Identificador de subcuenta')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=2, verbose_name='Identificador')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='DetailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=3, verbose_name='Identificador de Detalle')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=3, verbose_name='Identificador de subcuenta')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account', verbose_name='Cuenta Mayor')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.AddField(
            model_name='detailaccount',
            name='subaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.SubAccount', verbose_name='Sub-Cuenta'),
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.AccountCategory', verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa'),
        ),
    ]
