# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20170118_1703'),
        ('accounting', '0002_auto_20170120_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('detail', models.CharField(max_length=255, verbose_name='Detalle')),
                ('totalDebit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total Debe')),
                ('totalCredit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total Haber')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Diferencia')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
        ),
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Haber')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account', verbose_name='Cuenta')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
                ('detailAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DetailAccount', verbose_name='Cuenta Detalle')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entry', verbose_name='Asiento')),
                ('subAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.SubAccount', verbose_name='Sub-Cuenta')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Asientos - 1 .Detalles de Asiento',
            },
        ),
    ]
