# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='C\xf3digo de Barras'),
        ),
    ]
