# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170118_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdepartment',
            options={'ordering': ['id'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Productos - 1. Familias'},
        ),
        migrations.AlterModelOptions(
            name='productforsale',
            options={'ordering': ['code'], 'verbose_name': 'Producto para la Venta', 'verbose_name_plural': 'Productos - 3. Productos para la Venta'},
        ),
        migrations.AlterModelOptions(
            name='productsubdepartment',
            options={'ordering': ['id'], 'verbose_name': 'Sub-Familia', 'verbose_name_plural': 'Productos - 2. Sub-Familias'},
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa'),
        ),
    ]
