# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170119_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio sin Impuestos \u20a1'),
        ),
    ]
