# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_recipe_recipedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recipedetail',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recipedetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recipedetail',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeDetail',
        ),
    ]
